#############################################################################
##  v      #                   The Coq Proof Assistant                     ##
## <O___,, #                INRIA - CNRS - LIX - LRI - PPS                 ##
##   \VV/  #                                                               ##
##    //   #  Makefile automagically generated by coq_makefile Vtrunk      ##
#############################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

.DEFAULT_GOAL := all

# 
# This Makefile may take arguments passed as environment variables:
# COQBIN to specify the directory where Coq binaries resides;
# TIMECMD set a command to log .v compilation time;
# TIMED if non empty, use the default time command as TIMECMD;
# ZDEBUG/COQDEBUG to specify debug flags for ocamlc&ocamlopt/coqc;
# DSTROOT to specify a prefix to install path.

# Here is a hack to make $(eval $(shell works:
define donewline


endef
includecmdwithout@ = $(eval $(subst @,$(donewline),$(shell { $(1) | tr -d '\r' | tr '\n' '@'; })))
$(call includecmdwithout@,$(COQBIN)coqtop -config)

TIMED=
TIMECMD=
STDTIME?=/usr/bin/time -f "$* (user: %U mem: %M ko)"
TIMER=$(if $(TIMED), $(STDTIME), $(TIMECMD))

##########################
#                        #
# Libraries definitions. #
#                        #
##########################

COQLIBS?= -R . Fairisle
COQDOCLIBS?=-R . Fairisle

##########################
#                        #
# Variables definitions. #
#                        #
##########################


OPT?=
COQDEP?="$(COQBIN)coqdep" -c
COQFLAGS?=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQCHKFLAGS?=-silent -o
COQDOCFLAGS?=-interpolate -utf8
COQC?=$(TIMER) "$(COQBIN)coqc"
GALLINA?="$(COQBIN)gallina"
COQDOC?="$(COQBIN)coqdoc"
COQCHK?="$(COQBIN)coqchk"
COQMKTOP?="$(COQBIN)coqmktop"

##################
#                #
# Install Paths. #
#                #
##################

ifdef USERINSTALL
XDG_DATA_HOME?="$(HOME)/.local/share"
COQLIBINSTALL=$(XDG_DATA_HOME)/coq
COQDOCINSTALL=$(XDG_DATA_HOME)/doc/coq
else
COQLIBINSTALL="${COQLIB}user-contrib"
COQDOCINSTALL="${DOCDIR}user-contrib"
endif

######################
#                    #
# Files dispatching. #
#                    #
######################

VFILES:=Fairisle/PROOFS/Lemmas_Comb_Behaviour.v\
  Fairisle/PROOFS/Arbitration_Specif.v\
  Fairisle/PROOFS/Equiv_Struct_Beh_Arbitration.v\
  Fairisle/PROOFS/Invariant_a4_S.v\
  Fairisle/PROOFS/Timing_Proof.v\
  Fairisle/PROOFS/Timing_Arbiter.v\
  Fairisle/PROOFS/Arbitration_beh_sc.v\
  Fairisle/PROOFS/Arbitration_Proof.v\
  Fairisle/PROOFS/Arbiter4_Specif.v\
  Fairisle/PROOFS/Behaviour_Struct_lemmas.v\
  Fairisle/PROOFS/Arbiter4_Proof_lemmas.v\
  Fairisle/PROOFS/Lemmas_for_Arbitration.v\
  Fairisle/PROOFS/Arbiter4_Proof.v\
  Fairisle/PROOFS/PriorityDecode_Proof.v\
  Fairisle/SPECIF/GATES_AND_LATCHES/Gates.v\
  Fairisle/SPECIF/GATES_AND_LATCHES/Lemmas_Struct.v\
  Fairisle/SPECIF/GATES_AND_LATCHES/Gen_Gates_Del.v\
  Fairisle/SPECIF/GATES_AND_LATCHES/Base_Struct.v\
  Fairisle/SPECIF/GATES_AND_LATCHES/Gates_Del.v\
  Fairisle/SPECIF/ELEMENT/ElementComb.v\
  Fairisle/SPECIF/ELEMENT/ElementComb_Behaviour.v\
  Fairisle/SPECIF/ELEMENT/Base_Behaviour.v\
  Fairisle/SPECIF/ELEMENT/ElementTemp_Behaviour.v\
  Fairisle/SPECIF/ELEMENT/Arbitration.v\
  Fairisle/SPECIF/ELEMENT/ElementTemp.v\
  Fairisle/SPECIF/ELEMENT/Tools_Inf.v\
  Fairisle/SPECIF/ROUND_ROBIN/Lemmas_on_fcts.v\
  Fairisle/SPECIF/ROUND_ROBIN/NextPort.v\
  Fairisle/SPECIF/ROUND_ROBIN/RoundRobin.v\
  Fairisle/SPECIF/ROUND_ROBIN/SuccessfulInput.v\
  Fairisle/SPECIF/ROUND_ROBIN/PortsCompl.v\
  Fairisle/SPECIF/ROUND_ROBIN/PickSuccessfulInput.v\
  Fairisle/SPECIF/ROUND_ROBIN/TypePorts.v\
  Libraries/Lib_Arithmetic/Lib_Minus.v\
  Libraries/Lib_Arithmetic/Lib_Dec.v\
  Libraries/Lib_Arithmetic/Lib_Mult.v\
  Libraries/Lib_Arithmetic/Arith_Compl.v\
  Libraries/Lib_Arithmetic/Lib_Exp.v\
  Libraries/Lib_Arithmetic/Syntactic_Def.v\
  Libraries/Lib_Arithmetic/Lib_Eq_Le_Lt.v\
  Libraries/Lib_Arithmetic/Lib_Fact.v\
  Libraries/Lib_Arithmetic/Compare_Nat.v\
  Libraries/Lib_Arithmetic/Lib_Square.v\
  Libraries/Lib_Arithmetic/Lib_Plus.v\
  Libraries/Lib_Arithmetic/Lib_Pred.v\
  Libraries/Lib_Arithmetic/Lib_Div_Even_Odd.v\
  Libraries/Lib_Lists/Lists_of_lists.v\
  Libraries/Lib_Lists/Dependent_lists_Compl.v\
  Libraries/Lib_Lists/Manip_BoolLists.v\
  Libraries/Lib_Lists/Fixed_dLists.v\
  Libraries/Lib_Lists/Conversions.v\
  Libraries/Lib_Lists/dlist_Compl.v\
  Libraries/Lib_Lists/Dependent_lists.v\
  Libraries/Lib_Lists/Tests_in_d_lists.v\
  Libraries/Lib_Lists/PolyList_dlist.v\
  Libraries/Lib_Lists/Infinite_lists.v\
  Libraries/Lib_Lists/Proj_lists.v\
  Libraries/Lib_Boolean/Lib_Zerob.v\
  Libraries/Lib_Boolean/Bool_Compl.v\
  Libraries/Lib_Boolean/Lib_Bool.v\
  Libraries/Lib_Automata/Mealy.v\
  Libraries/Lib_Automata/Basic_composition_rules.v\
  Libraries/Lib_Automata/Moore_Mealy.v\
  Libraries/Lib_Automata/Identity.v\
  Libraries/Lib_Automata/Lemmas_on_Basic_rules.v\
  Libraries/Lib_Automata/Derived_composition_rules.v\
  Libraries/Lib_Automata/Moore.v\
  Libraries/Lib_Basis/Injections.v\
  Libraries/Lib_Basis/Product.v\
  Libraries/Lib_Basis/Lib_Set_Products.v\
  Libraries/Lib_Basis/Lib_Prop.v

-include $(addsuffix .d,$(VFILES))
.SECONDARY: $(addsuffix .d,$(VFILES))

VO=vo
VOFILES:=$(VFILES:.v=.$(VO))
GLOBFILES:=$(VFILES:.v=.glob)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)
ifeq '$(HASNATDYNLINK)' 'true'
HASNATDYNLINK_OR_EMPTY := yes
else
HASNATDYNLINK_OR_EMPTY :=
endif

#######################################
#                                     #
# Definition of the toplevel targets. #
#                                     #
#######################################

all: $(VOFILES) 

quick:
	$(MAKE) -f $(firstword $(MAKEFILE_LIST)) all VO=vi
checkproofs:
	$(COQC) $(COQDEBUG) $(COQFLAGS) -schedule-vi-checking $(J) $(VOFILES:%.vo=%.vi)
gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir -p html
	$(COQDOC) -toc $(COQDOCFLAGS) -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir -p html
	$(COQDOC) -toc $(COQDOCFLAGS) -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc $(COQDOCFLAGS) -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $^`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc $(COQDOCFLAGS) -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $^`

all.pdf: $(VFILES)
	$(COQDOC) -toc $(COQDOCFLAGS) -pdf $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $^`

all-gal.pdf: $(VFILES)
	$(COQDOC) -toc $(COQDOCFLAGS) -pdf -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $^`

validate: $(VOFILES)
	$(COQCHK) $(COQCHKFLAGS) $(COQLIBS) $(notdir $(^:.vo=))

beautify: $(VFILES:=.beautified)
	for file in $^; do mv $${file%.beautified} $${file%beautified}old && mv $${file} $${file%.beautified}; done
	@echo 'Do not do "make clean" until you are sure that everything went well!'
	@echo 'If there were a problem, execute "for file in $$(find . -name \*.v.old -print); do mv $${file} $${file%.old}; done" in your shell/'

.PHONY: all opt byte archclean clean install uninstall_me.sh uninstall userinstall depend html validate

####################
#                  #
# Special targets. #
#                  #
####################

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

userinstall:
	+$(MAKE) USERINSTALL=true install

install:
	cd "." && for i in $(VOFILES) $(CMOFILES) $(CMIFILES) $(CMAFILES); do \
	 install -d "`dirname "$(DSTROOT)"$(COQLIBINSTALL)/Fairisle/$$i`"; \
	 install -m 0644 $$i "$(DSTROOT)"$(COQLIBINSTALL)/Fairisle/$$i; \
	done

install-doc:
	install -d "$(DSTROOT)"$(COQDOCINSTALL)/Fairisle/html
	for i in html/*; do \
	 install -m 0644 $$i "$(DSTROOT)"$(COQDOCINSTALL)/Fairisle/$$i;\
	done

uninstall_me.sh:
	echo '#!/bin/sh' > $@ 
	printf 'cd "$${DSTROOT}"$(COQLIBINSTALL)/Fairisle && rm -f $(VOFILES) $(CMOFILES) $(CMIFILES) $(CMAFILES) && find . -type d -and -empty -delete\ncd "$${DSTROOT}"$(COQLIBINSTALL) && find "Fairisle" -maxdepth 0 -and -empty -exec rmdir -p \{\} \;\n' >> "$@"
	printf 'cd "$${DSTROOT}"$(COQDOCINSTALL)/Fairisle \\\n' >> "$@"
	printf '&& rm -f $(shell find "html" -maxdepth 1 -and -type f -print)\n' >> "$@"
	printf 'cd "$${DSTROOT}"$(COQDOCINSTALL) && find Fairisle/html -maxdepth 0 -and -empty -exec rmdir -p \{\} \;\n' >> "$@"
	chmod +x $@

uninstall: uninstall_me.sh
	sh $<

clean:
	rm -f $(VOFILES) $(VOFILES:.vo=.vi) $(GFILES) $(VFILES:.v=.v.d) $(VFILES:=.beautified) $(VFILES:=.old)
	rm -f all.ps all-gal.ps all.pdf all-gal.pdf all.glob $(VFILES:.v=.glob) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) all-mli.tex
	- rm -rf html mlihtml uninstall_me.sh

archclean:
	rm -f *.cmx *.o

printenv:
	@"$(COQBIN)coqtop" -config
	@echo 'CAMLC =	$(CAMLC)'
	@echo 'CAMLOPTC =	$(CAMLOPTC)'
	@echo 'PP =	$(PP)'
	@echo 'COQFLAGS =	$(COQFLAGS)'
	@echo 'COQLIBINSTALL =	$(COQLIBINSTALL)'
	@echo 'COQDOCINSTALL =	$(COQDOCINSTALL)'

Makefile: Make
	mv -f $@ $@.bak
	"$(COQBIN)coq_makefile" -f $< -o $@


###################
#                 #
# Implicit rules. #
#                 #
###################

%.vo %.glob: %.v
	$(COQC) $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -quick $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) $(COQDOCFLAGS) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) $(COQDOCFLAGS) -html $< -o $@

%.g.tex: %.v
	$(COQDOC) $(COQDOCFLAGS) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) $(COQDOCFLAGS)  -html -g $< -o $@

%.v.d: %.v
	$(COQDEP) $(COQLIBS) "$<" > "$@" || ( RV=$$?; rm -f "$@"; exit $${RV} )

%.v.beautified:
	$(COQC) $(COQDEBUG) $(COQFLAGS) -beautify $*

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

