##########################################################################
##  v      #                  The Coq Proof Assistant                   ##
## <O___,, # CNRS-Ecole Polytechnique-INRIA Futurs-Universite Paris Sud ##
##   \VV/  #                                                            ##
##    //   #   Makefile automagically generated by coq_makefile V8.2    ##
##########################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

#########################
#                       #
# Libraries definition. #
#                       #
#########################

OCAMLLIBS:=
COQLIBS:= -R . fairisle
COQDOCLIBS:=-R . fairisle

##########################
#                        #
# Variables definitions. #
#                        #
##########################

CAMLP4LIB:=$(shell $(CAMLBIN)camlp5 -where 2> /dev/null || $(CAMLBIN)camlp4 -where)
CAMLP4:=$(notdir $(CAMLP4LIB))
COQSRC:=-I $(COQTOP)/kernel -I $(COQTOP)/lib \
  -I $(COQTOP)/library -I $(COQTOP)/parsing \
  -I $(COQTOP)/pretyping -I $(COQTOP)/interp \
  -I $(COQTOP)/proofs -I $(COQTOP)/syntax -I $(COQTOP)/tactics \
  -I $(COQTOP)/toplevel -I $(COQTOP)/contrib/correctness \
  -I $(COQTOP)/contrib/extraction -I $(COQTOP)/contrib/field \
  -I $(COQTOP)/contrib/fourier -I $(COQTOP)/contrib/graphs \
  -I $(COQTOP)/contrib/interface -I $(COQTOP)/contrib/jprover \
  -I $(COQTOP)/contrib/omega -I $(COQTOP)/contrib/romega \
  -I $(COQTOP)/contrib/ring -I $(COQTOP)/contrib/xml \
  -I $(CAMLP4LIB)
ZFLAGS:=$(OCAMLLIBS) $(COQSRC)
OPT:=
COQFLAGS:=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQC:=$(COQBIN)coqc
COQDEP:=$(COQBIN)coqdep -c
GALLINA:=$(COQBIN)gallina
COQDOC:=$(COQBIN)coqdoc
CAMLC:=$(CAMLBIN)ocamlc -rectypes -c
CAMLOPTC:=$(CAMLBIN)ocamlopt -c
CAMLLINK:=$(CAMLBIN)ocamlc
CAMLOPTLINK:=$(CAMLBIN)ocamlopt
GRAMMARS:=grammar.cma
CAMLP4EXTEND:=pa_extend.cmo pa_macro.cmo q_MLast.cmo
PP:=-pp "$(CAMLBIN)$(CAMLP4)o -I . -I $(COQTOP)/parsing $(CAMLP4EXTEND) $(GRAMMARS) -impl"

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES:=./Libraries/Lib_Basis/Lib_Prop.v\
  ./Libraries/Lib_Basis/Lib_Set_Products.v\
  ./Libraries/Lib_Basis/Product.v\
  ./Libraries/Lib_Basis/Injections.v\
  ./Libraries/Lib_Automata/Moore.v\
  ./Libraries/Lib_Automata/Derived_composition_rules.v\
  ./Libraries/Lib_Automata/Lemmas_on_Basic_rules.v\
  ./Libraries/Lib_Automata/Identity.v\
  ./Libraries/Lib_Automata/Moore_Mealy.v\
  ./Libraries/Lib_Automata/Basic_composition_rules.v\
  ./Libraries/Lib_Automata/Mealy.v\
  ./Libraries/Lib_Boolean/Lib_Bool.v\
  ./Libraries/Lib_Boolean/Bool_Compl.v\
  ./Libraries/Lib_Boolean/Lib_Zerob.v\
  ./Libraries/Lib_Lists/Proj_lists.v\
  ./Libraries/Lib_Lists/Infinite_lists.v\
  ./Libraries/Lib_Lists/PolyList_dlist.v\
  ./Libraries/Lib_Lists/Tests_in_d_lists.v\
  ./Libraries/Lib_Lists/Dependent_lists.v\
  ./Libraries/Lib_Lists/dlist_Compl.v\
  ./Libraries/Lib_Lists/Conversions.v\
  ./Libraries/Lib_Lists/Fixed_dLists.v\
  ./Libraries/Lib_Lists/Manip_BoolLists.v\
  ./Libraries/Lib_Lists/Dependent_lists_Compl.v\
  ./Libraries/Lib_Lists/Lists_of_lists.v\
  ./Libraries/Lib_Arithmetic/Lib_Div_Even_Odd.v\
  ./Libraries/Lib_Arithmetic/Lib_Pred.v\
  ./Libraries/Lib_Arithmetic/Lib_Plus.v\
  ./Libraries/Lib_Arithmetic/Lib_Square.v\
  ./Libraries/Lib_Arithmetic/Compare_Nat.v\
  ./Libraries/Lib_Arithmetic/Lib_Fact.v\
  ./Libraries/Lib_Arithmetic/Lib_Eq_Le_Lt.v\
  ./Libraries/Lib_Arithmetic/Syntactic_Def.v\
  ./Libraries/Lib_Arithmetic/Lib_Exp.v\
  ./Libraries/Lib_Arithmetic/Arith_Compl.v\
  ./Libraries/Lib_Arithmetic/Lib_Mult.v\
  ./Libraries/Lib_Arithmetic/Lib_Dec.v\
  ./Libraries/Lib_Arithmetic/Lib_Minus.v\
  ./Fairisle/SPECIF/ROUND_ROBIN/TypePorts.v\
  ./Fairisle/SPECIF/ROUND_ROBIN/PickSuccessfulInput.v\
  ./Fairisle/SPECIF/ROUND_ROBIN/PortsCompl.v\
  ./Fairisle/SPECIF/ROUND_ROBIN/SuccessfulInput.v\
  ./Fairisle/SPECIF/ROUND_ROBIN/RoundRobin.v\
  ./Fairisle/SPECIF/ROUND_ROBIN/NextPort.v\
  ./Fairisle/SPECIF/ROUND_ROBIN/Lemmas_on_fcts.v\
  ./Fairisle/SPECIF/ELEMENT/Tools_Inf.v\
  ./Fairisle/SPECIF/ELEMENT/ElementTemp.v\
  ./Fairisle/SPECIF/ELEMENT/Arbitration.v\
  ./Fairisle/SPECIF/ELEMENT/ElementTemp_Behaviour.v\
  ./Fairisle/SPECIF/ELEMENT/Base_Behaviour.v\
  ./Fairisle/SPECIF/ELEMENT/ElementComb_Behaviour.v\
  ./Fairisle/SPECIF/ELEMENT/ElementComb.v\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Gates_Del.v\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Base_Struct.v\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Gen_Gates_Del.v\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Lemmas_Struct.v\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Gates.v\
  ./Fairisle/PROOFS/PriorityDecode_Proof.v\
  ./Fairisle/PROOFS/Arbiter4_Proof.v\
  ./Fairisle/PROOFS/Lemmas_for_Arbitration.v\
  ./Fairisle/PROOFS/Arbiter4_Proof_lemmas.v\
  ./Fairisle/PROOFS/Behaviour_Struct_lemmas.v\
  ./Fairisle/PROOFS/Arbiter4_Specif.v\
  ./Fairisle/PROOFS/Arbitration_Proof.v\
  ./Fairisle/PROOFS/Arbitration_beh_sc.v\
  ./Fairisle/PROOFS/Timing_Arbiter.v\
  ./Fairisle/PROOFS/Timing_Proof.v\
  ./Fairisle/PROOFS/Invariant_a4_S.v\
  ./Fairisle/PROOFS/Equiv_Struct_Beh_Arbitration.v\
  ./Fairisle/PROOFS/Arbitration_Specif.v\
  ./Fairisle/PROOFS/Lemmas_Comb_Behaviour.v
VOFILES:=$(VFILES:.v=.vo)
GLOBFILES:=$(VFILES:.v=.glob)
VIFILES:=$(VFILES:.v=.vi)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)

all: ./Libraries/Lib_Basis/Lib_Prop.vo\
  ./Libraries/Lib_Basis/Lib_Set_Products.vo\
  ./Libraries/Lib_Basis/Product.vo\
  ./Libraries/Lib_Basis/Injections.vo\
  ./Libraries/Lib_Automata/Moore.vo\
  ./Libraries/Lib_Automata/Derived_composition_rules.vo\
  ./Libraries/Lib_Automata/Lemmas_on_Basic_rules.vo\
  ./Libraries/Lib_Automata/Identity.vo\
  ./Libraries/Lib_Automata/Moore_Mealy.vo\
  ./Libraries/Lib_Automata/Basic_composition_rules.vo\
  ./Libraries/Lib_Automata/Mealy.vo\
  ./Libraries/Lib_Boolean/Lib_Bool.vo\
  ./Libraries/Lib_Boolean/Bool_Compl.vo\
  ./Libraries/Lib_Boolean/Lib_Zerob.vo\
  ./Libraries/Lib_Lists/Proj_lists.vo\
  ./Libraries/Lib_Lists/Infinite_lists.vo\
  ./Libraries/Lib_Lists/PolyList_dlist.vo\
  ./Libraries/Lib_Lists/Tests_in_d_lists.vo\
  ./Libraries/Lib_Lists/Dependent_lists.vo\
  ./Libraries/Lib_Lists/dlist_Compl.vo\
  ./Libraries/Lib_Lists/Conversions.vo\
  ./Libraries/Lib_Lists/Fixed_dLists.vo\
  ./Libraries/Lib_Lists/Manip_BoolLists.vo\
  ./Libraries/Lib_Lists/Dependent_lists_Compl.vo\
  ./Libraries/Lib_Lists/Lists_of_lists.vo\
  ./Libraries/Lib_Arithmetic/Lib_Div_Even_Odd.vo\
  ./Libraries/Lib_Arithmetic/Lib_Pred.vo\
  ./Libraries/Lib_Arithmetic/Lib_Plus.vo\
  ./Libraries/Lib_Arithmetic/Lib_Square.vo\
  ./Libraries/Lib_Arithmetic/Compare_Nat.vo\
  ./Libraries/Lib_Arithmetic/Lib_Fact.vo\
  ./Libraries/Lib_Arithmetic/Lib_Eq_Le_Lt.vo\
  ./Libraries/Lib_Arithmetic/Syntactic_Def.vo\
  ./Libraries/Lib_Arithmetic/Lib_Exp.vo\
  ./Libraries/Lib_Arithmetic/Arith_Compl.vo\
  ./Libraries/Lib_Arithmetic/Lib_Mult.vo\
  ./Libraries/Lib_Arithmetic/Lib_Dec.vo\
  ./Libraries/Lib_Arithmetic/Lib_Minus.vo\
  ./Fairisle/SPECIF/ROUND_ROBIN/TypePorts.vo\
  ./Fairisle/SPECIF/ROUND_ROBIN/PickSuccessfulInput.vo\
  ./Fairisle/SPECIF/ROUND_ROBIN/PortsCompl.vo\
  ./Fairisle/SPECIF/ROUND_ROBIN/SuccessfulInput.vo\
  ./Fairisle/SPECIF/ROUND_ROBIN/RoundRobin.vo\
  ./Fairisle/SPECIF/ROUND_ROBIN/NextPort.vo\
  ./Fairisle/SPECIF/ROUND_ROBIN/Lemmas_on_fcts.vo\
  ./Fairisle/SPECIF/ELEMENT/Tools_Inf.vo\
  ./Fairisle/SPECIF/ELEMENT/ElementTemp.vo\
  ./Fairisle/SPECIF/ELEMENT/Arbitration.vo\
  ./Fairisle/SPECIF/ELEMENT/ElementTemp_Behaviour.vo\
  ./Fairisle/SPECIF/ELEMENT/Base_Behaviour.vo\
  ./Fairisle/SPECIF/ELEMENT/ElementComb_Behaviour.vo\
  ./Fairisle/SPECIF/ELEMENT/ElementComb.vo\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Gates_Del.vo\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Base_Struct.vo\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Gen_Gates_Del.vo\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Lemmas_Struct.vo\
  ./Fairisle/SPECIF/GATES_AND_LATCHES/Gates.vo\
  ./Fairisle/PROOFS/PriorityDecode_Proof.vo\
  ./Fairisle/PROOFS/Arbiter4_Proof.vo\
  ./Fairisle/PROOFS/Lemmas_for_Arbitration.vo\
  ./Fairisle/PROOFS/Arbiter4_Proof_lemmas.vo\
  ./Fairisle/PROOFS/Behaviour_Struct_lemmas.vo\
  ./Fairisle/PROOFS/Arbiter4_Specif.vo\
  ./Fairisle/PROOFS/Arbitration_Proof.vo\
  ./Fairisle/PROOFS/Arbitration_beh_sc.vo\
  ./Fairisle/PROOFS/Timing_Arbiter.vo\
  ./Fairisle/PROOFS/Timing_Proof.vo\
  ./Fairisle/PROOFS/Invariant_a4_S.vo\
  ./Fairisle/PROOFS/Equiv_Struct_Beh_Arbitration.vo\
  ./Fairisle/PROOFS/Arbitration_Specif.vo\
  ./Fairisle/PROOFS/Lemmas_Comb_Behaviour.vo

spec: $(VIFILES)

gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html

.SUFFIXES: .v .vo .vi .g .html .tex .g.tex .g.html

%.vo %.glob: %.v
	$(COQC) -dump-glob $*.glob $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob  -html $< -o $@

%.g.tex: %.v
	$(COQDOC) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob -html -g $< -o $@

%.v.d.raw: %.v
	$(COQDEP) -slash $(COQLIBS) "$<" > "$@"\
	  || ( RV=$$?; rm -f "$@"; exit $${RV} )

%.v.d: %.v.d.raw
	$(HIDE)sed 's/\(.*\)\.vo[[:space:]]*:/\1.vo \1.glob:/' < "$<" > "$@" \
	  || ( RV=$$?; rm -f "$@"; exit $${RV} )

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

install:
	mkdir -p `$(COQC) -where`/user-contrib
	cp -f $(VOFILES) `$(COQC) -where`/user-contrib

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile


clean:
	rm -f *.cmo *.cmi *.cmx *.o $(VOFILES) $(VIFILES) $(GFILES) *~
	rm -f all.ps all-gal.ps all.glob $(VFILES:.v=.glob) $(HTMLFILES) $(GHTMLFILES) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) $(VFILES:.v=.v.d)
	- rm -rf html

archclean:
	rm -f *.cmx *.o


-include $(VFILES:.v=.v.d)
.SECONDARY: $(VFILES:.v=.v.d)

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

